version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"


#  api:
#    build: .
#    ports:
#      - "3000:3000"
#    environment:
#      - MONGO_URI=mongodb://root:password@mongo:27017/
#    depends_on:
#      - mongo

volumes:
  mongo-data: