version: "3.9"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myadminuser
      - MONGO_INITDB_ROOT_PASSWORD=myadminpassword # **STRONG PASSWORD REQUIRED**
    restart: always

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=myadminuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=myadminpassword # **STRONG PASSWORD REQUIRED**
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb_data: