version: '3'

services:
  dbwarehouse:
    image: mongo:4.2
    container_name: warehouse-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    container_name: warehouse-mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=dbwarehouse
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    ports:
      - "8081:8081"
    depends_on:
      - dbwarehouse

volumes:
  mongo-data: